# AllCops:
# RunRailsCops: true

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 1200

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 1200

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails:
  Enabled: true
