# AllCops:
# RunRailsCops: true

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Metrics/LineLength:
  Max: 1200

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 1200

Metrics/CyclomaticComplexity:
    Enabled: true

Metrics/AbcSize:
  Enabled: true

Rails:
  Enabled: true
