language: ruby

rvm:
  - 2.3.1

addons:
  postgresql: "9.4"

services:
  - postgresql

bundler_args: --without production development

before_script:
  - psql -c 'create database gwx_test;' -U postgres
  - cp config/yetting.example.yml config/yetting.yml
  - cp config/secrets.example.yml config/secrets.yml
  - cp config/database.example.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate

script: RAILS_ENV=test bundle exec rails test
