# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa27e5c61a2621b91574beb83cdfb0970c023821c8fe242cff71c23bf460ae9f8e3b05ee051106f83caece608eafd7fe6200c986f044cb7c7a9f1540a1fd4f5c

test:
  secret_key_base: 38ebb2391312db2f5bf3f218e8ea22632fa706714815bcc426a9146f706c79a15d99dc709ded863e5252b438e8dd7b08dcab0f7ed30db307ef95bdc61d9a316c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 50665e882d496c77f7bed137962394042ee088419053183794957f74975bc7d33160978201a5aa959bda715f82c7878ec244bab5e726ac1d5ab8007f4a138c71
