defaults: &defaults
  app_name: 'GLZ'
  admin: 'glzztt@gmail.com'
  admin_password: 'glz1992'
  admin_mobile: '13730820749'
  admin_session_login: 'glz1992loveztt'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
